### PR TITLE
Updated to: 9c729ba8aa2bbd5844293e096fdd061d4595d13b

### PR DESCRIPTION
**Pull request by RensDofferhoff**

### CODE REVIEW

**Comment by RensDofferhoff** [comment]
I will add the new sys dependency tommorow

**Comment by tomtomme** [comment]
@RensDofferhoff 
This beta is a crashfest :D
Just crashes all the time, even when just clicking a ribbon button. Also the data library is completely missing :D 
The one before was much more stable and had a data library!

**Comment by RensDofferhoff** [comment]
> @RensDofferhoff This beta is a crashfest :D Just crashes all the time, even when just clicking a ribbon button. Also the data library is completely missing :D The one before was much more stable and had a data library!

I can see the missing datalib as well but what ribbon button are you pressing to cause a crash?

**Comment by tomtomme** [comment]
atm I can not reproduce it. It was mainly, when I edited data and came back to analysis. But seems random. Maybe it had something to do with some of the exotic datasets I test. Will investigate and get back to you if I have something more solid.

**Comment by RensDofferhoff** [comment]
Thanks for your efforts! I will go see if I can get the datalib back :p

**Comment by RensDofferhoff** [comment]
I found the issue and will resolve it

**Pull request merged**
