### PR TITLE
Updated to: b5921fe65e9c8fdcc8f4053e18857ae317feb93f

### PR DESCRIPTION
**Pull request by RensDofferhoff**

### CODE REVIEW

**Comment by tomtomme** [comment]
@RensDofferhoff 
I tried to install the 2 repos via the above command, but both give me a "404"

```
flatpak install --user https://dl.flathub.org/build-repo/79165/org.jaspstats.JASP.flatpakref
Fehler: Can't load uri https://dl.flathub.org/build-repo/79165/org.jaspstats.JASP.flatpakref: Server returned status 404
```

Am I doing something wrong?
Maybe we should also detail how to install these testing versions on the "nightlies" page. If I understand correclty the "beta" builds are less recent than these "testing" builds. And the last available beta is now already a month old.

**Comment by RensDofferhoff** [comment]
Apologies. I have been (still am) sick and forgot to merge this. It will be on the beta repo soon

**Comment by tomtomme** [comment]
get well soon!

**Comment by RensDofferhoff** [comment]
This is an automated system provided by flathub so we can not change it.
The files on //test are probably already removed. but let me make a new PR

**Pull request merged**
