### PR TITLE
[TEST] Update runtime to Qt6.5

### PR DESCRIPTION
**Pull request by shun2wang**
Fixes: https://github.com/jasp-stats/jasp-issues/issues/2296

### CODE REVIEW

**Comment by bbhtt** [comment]
bot, build

**Comment by bbhtt** [comment]
bot, build

**Comment by bbhtt** [comment]
Looks like there is some infra issue that makes the build stuck. Please wait for that to be fixed. I manually triggered https://buildbot.flathub.org/#/builders/6/builds/81722

It is failing on:

```
In file included from /run/build/qt5compat/src/core5/sax/qxml.cpp:10:
/run/build/qt5compat/src/core5/sax/qxml_p.h:52:9: error: ISO C++ forbids declaration of ‘Q_DUMMY_COMPARISON_OPERATOR’ with no type [-fpermissive]
   52 |         Q_DUMMY_COMPARISON_OPERATOR(ExternParameterEntity)
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/run/build/qt5compat/src/core5/sax/qxml_p.h:52:58: error: expected ‘;’ at end of member declaration
   52 |         Q_DUMMY_COMPARISON_OPERATOR(ExternParameterEntity)
      |                                                          ^
      |                                                           ;
/run/build/qt5compat/src/core5/sax/qxml_p.h:64:9: error: ISO C++ forbids declaration of ‘Q_DUMMY_COMPARISON_OPERATOR’ with no type [-fpermissive]
   64 |         Q_DUMMY_COMPARISON_OPERATOR(ExternEntity)
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/run/build/qt5compat/src/core5/sax/qxml_p.h:64:49: error: expected ‘;’ at end of member declaration
   64 |         Q_DUMMY_COMPARISON_OPERATOR(ExternEntity)
      |                                                 ^
      |                                                  ;
make[2]: *** [src/core5/CMakeFiles/Core5Compat.dir/build.make:122: src/core5/CMakeFiles/Core5Compat.dir/sax/qxml.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 97%] Linking CXX shared module ../../../qml/Qt5Compat/GraphicalEffects/libqtgraphicaleffectsplugin.so
[ 97%] Built target qtgraphicaleffectsplugin
make[1]: *** [CMakeFiles/Makefile2:993: src/core5/CMakeFiles/Core5Compat.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 98%] Linking CXX shared module ../../../../qml/Qt5Compat/GraphicalEffects/private/libqtgraphicaleffectsprivateplugin.so
[ 98%] Built target qtgraphicaleffectsprivate
make: *** [Makefile:146: all] Error 2
FB: host_command_exited_cb 1937438 512
```

**Comment by shun2wang** [comment]
bot, build

**Comment by shun2wang** [comment]
it still not start build...

**Comment by bbhtt** [comment]
bot, build

**Comment by bbhtt** [comment]
https://buildbot.flathub.org/#/builders/6/builds/81771

**Pull request closed without merging**
